server:
  port: 10_003

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: job-service

home-garden:
  endpoints:
    room-graphql: http://localhost:8000/api/rooms
    device-graphql: http://localhost:8000/api/devices
