server:
  port: 10_000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: room-service
  graphql:
    path: /api/rooms
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/home-garden?currentSchema=rooms
    username: dev_user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    create-schemas: true
