server:
  port: 10_007

eureka:
  client:
    interface: eth0
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: platform-dictionary-service
  graphql:
    path: /api/platform/dictionary
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/home-garden?currentSchema=dictionary-service
    username: dev_user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    create-schemas: true
