spring:
  application:
    name: platform-dictionary-service
  datasource:
    url: jdbc:postgresql://localhost:5432/home-garden?currentSchema=platform-user-profile-service
    username: dev_user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    create-schemas: true
