version: "3.9"

services:

  postgresql:
    image: postgres:14-bullseye
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=home-garden
    deploy:
      replicas: 1

  service-discovery:
    image: smirnoke/home-project-service-discovery:latest
    ports:
      - 9000:9000
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 384Mb
    configs:
      - source: service-discovery-bootstrap.yml
        target: /application/config/bootstrap.yml

volumes:
  postgresql_data:

configs:
  service-discovery-bootstrap.yml:
    file:
