version: "3.9"

services:

  postgresql:
    image: postgres:14-bullseye
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=home-garden
