ALTER TABLE OPERATION DROP COLUMN SOURCE_CURRENCY;
ALTER TABLE OPERATION DROP COLUMN DESTINATION_CURRENCY;

ALTER TABLE OPERATION ADD COLUMN SOURCE_CURRENCY VARCHAR(36);
ALTER TABLE OPERATION ADD COLUMN DESTINATION_CURRENCY VARCHAR(36);