server:
  port: 11100

logging:
  level:
    org:
      atmosphere : warn

home-project:
  http:
    client:
      feign:
        enabled: true

ui:
  oauth:
    uri: /oauth2/authorization/google

spring:
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: XXXX
            client-secret: YYYY
vaadin:
  allowed-packages: com.vaadin,org.vaadin,dev.hilla,com.smirnoff.home.ui

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true
