server:
  port: 10_002

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: device-command-service
  graphql:
    path: /api/device-commands
    graphiql:
      enabled: true

connector:
  ak: XXXXX
  sk: XXXXX
  region: US
