CREATE TABLE "USER"
(
    ID         VARCHAR(36) PRIMARY KEY NOT NULL,
    FIRSTNAME  VARCHAR(50)             NOT NULL,
    LASTNAME   VARCHAR(50)             NOT NULL,
    COMPANY_ID VARCHAR(50)             NOT NULL
);

ALTER TABLE "USER" ADD CONSTRAINT FK_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES "COMPANY"(ID);