server:
  port: 10_001

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9000/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: device-service
  graphql:
    path: /api/devices
    graphiql:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/home-garden?currentSchema=device
    username: dev_user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    create-schemas: true

home-garden:
  endpoints:
    room-graphql: http://localhost:8000/api/rooms
    device-command-graphql: http://localhost:10002/api/device-commands
